/**
 * @file Argon2id key derivation worker thread.
 *
 * Runs Argon2id (RFC 9106) in a dedicated worker thread so the Electron main
 * process never blocks during the memory-hard derivation (64-512 MiB, 2-25s).
 *
 * The worker receives its input via `workerData`, derives the key synchronously,
 * posts the result back as a plain array (structured clone safe), then zeroizes
 * sensitive memory and exits.
 *
 * This file MUST have a .mjs extension because it uses ESM `import` syntax and
 * the project's package.json does not set `"type": "module"`. Node.js loads
 * worker_threads files as CommonJS by default; the .mjs extension forces ESM
 * loading.
 *
 * @module argon-worker
 */

import { parentPort, workerData } from "worker_threads";
import { argon2id } from "@noble/hashes/argon2.js";
import { utf8ToBytes } from "@noble/ciphers/utils.js";

const { password, salt, params } = workerData;

/** @type {Uint8Array} Password bytes (string or array from main thread) */
const passwordBytes = typeof password === "string"
    ? utf8ToBytes(password)
    : new Uint8Array(password);

/** @type {Uint8Array} Salt bytes (32 bytes, CSPRNG-generated by main thread) */
const saltBytes = new Uint8Array(salt);

/**
 * Derive a 32-byte AES-256 key using Argon2id.
 *
 * @param {Uint8Array} passwordBytes - Password input.
 * @param {Uint8Array} saltBytes - 32-byte salt.
 * @param {{ t: number, m: number, p: number, dkLen?: number }} params
 *   Argon2id parameters:
 *   - `t` — time cost (iterations)
 *   - `m` — memory cost in KiB
 *   - `p` — parallelism (threads)
 *   - `dkLen` — desired key length in bytes (default 32)
 * @returns {Uint8Array} Derived key (32 bytes).
 */
const key = argon2id(passwordBytes, saltBytes, params);

/**
 * Send the derived key back to the main thread as a plain array.
 * Uint8Array cannot be sent via structured clone in all environments;
 * Array is universally safe.
 */
parentPort.postMessage(Array.from(key));

/** Zeroize sensitive memory before exiting. */
passwordBytes.fill(0);
key.fill(0);
process.exit(0);
