let _blockchains = {
    BEOS: {
        coreSymbol: "BEOS",
        name: "BEOSmainnet",
        chainId: "cbef47b0b26d2b8407ec6a6f91284100ec32d288a39d4b4bbd49655f7c484112",
        nodeList: [
            { url: "https://api.beos.world" },
        ],
    },
    BTS: {
        coreSymbol: "BTS",
        name: "BitShares",
        chainId: "4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8",
        nodeList: [
            { url: "wss://node.xbts.io/ws" },
            { url: "wss://api.bts.mobi/ws" },
            { url: "wss://nexus01.co.uk/ws" },
            { url: "wss://dex.iobanker.com/ws" },
            { url: "wss://api.dex.trading/" },
            { url: "wss://api.bitshares.bhuz.info/ws" },
            { url: "wss://btsws.roelandp.nl/ws" },
        ],
    },
    BTS_TEST: {
        coreSymbol: "TEST",
        name: "BitShares",
        testnet: true,
        chainId: "39f5e2ede1f8bc1a3a54a7914414e3779e33193f1f5693510e73cb7a87617447",
        nodeList: [
            { url: "wss://testnet.xbts.io/ws" },
            { url: "wss://testnet.dex.trading/" },
            { url: "wss://api-testnet.61bts.com/ws" },
            { url: "wss://testnet.bitshares.im/ws" },
        ],
    },
    EOS: {
        coreSymbol: "EOS",
        name: "EOSmainnet",
        chainId: "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
        nodeList: [
            { url: "https://eos.greymass.com" },
            { url: "https://eos.eosusa.io" },
            { url: "https://eos.eosphere.io" },
            { url: "https://vaulta-hyperion.eosphere.io" },
            { url: "https://api.eossupport.io" },
            { url: "https://eos.newdex.one" },
            { url: "https://api.main.alohaeos.com" },
            { url: "https://mainnet.eosio.sg" },
            { url: "https://api.eos.detroitledger.tech" },
            { url: "https://api.eosrio.io" },
            { url: "https://eos.hyperion.eosrio.io" },
            { url: "https://api.eos.cryptolions.io" },
            { url: "https://mainnet.genereos.io" },
            { url: "https://mainnet.eosamsterdam.net" },
            { url: "https://hyperion-v2.eospglmlt.com" },
            { url: "https://hyperion-v2.hufi.io" },
            { url: "https://api.eos42.io" },
            { url: "https://api.eosrapid.com" },
            { url: "https://eospush.tokenpocket.pro" },
        ],
    },
    EOSTEST: {
        coreSymbol: "EOS",
        name: "EOS Testnet",
        testnet: true,
        chainId: "73e4385a2708e6d7048834fbc1079f2fabb17b3c125b146af438971e90716c4d",
        nodeList: [
            { url: "https://jungle4.cryptolions.io:443" },
            { url: "https://jungle4.eosphere.io:443" },
            { url: "https://jungle4.api.eosnation.io:443" },
        ],
    },
    FIO: {
        coreSymbol: "FIO",
        name: "FIO",
        chainId: "21dcae42c0182200e93f954a074011f9048a7624c6fe81d3c9541a614a88bd1c",
        nodeList: [
            { url: "https://fio.eosphere.io" },
            { url: "https://fio.blockpane.com" },
            { url: "https://fio.cryptolions.io" },
            { url: "https://fio.genereos.io" },
            { url: "https://api.fio.detroitledger.tech" },
            { url: "https://fio.eosusa.io" },
            { url: "https://fio.eos.barcelona" },
            { url: "https://api.fio.alohaeos.com" },
            { url: "https://api-fio.nodeone.network:8344" },
            { url: "https://fio.eu.eosamsterdam.net" },
            { url: "https://api.fiosweden.org" },
            { url: "https://fioapi.ledgerwise.io" },
            { url: "https://fio-api.eosiomadrid.io" },
            { url: "https://fio.eosrio.io" },
            { url: "https://fio.eosargentina.io" },
            { url: "https://fio.eosdublin.io" },
            { url: "https://dmail.dedyn.io" },
            { url: "https://api.fio.greeneosio.com" },
            { url: "https://api.fio.blocksindia.com" },
            { url: "https://fio.eosdac.io" },
            { url: "https://fio.greymass.com/" }
        ],
    },
    FIOTEST: {
        coreSymbol: "FIO",
        name: "FIO Testnet",
        testnet: true,
        chainId:
            "b20901380af44ef59c5918439a1f9a41d83669020319a80574b804a5f95cbd7e",
        nodeList: [
            { url: "https://test.fio.eosusa.io" },
            { url: "https://fiotestnet.greymass.com/" },
            { url: "https://fio-testnet.eosphere.io" }
        ],
    },
    LIBRE: {
        coreSymbol: "LIBRE",
        name: "Libre",
        chainId: "38b1d7815474d0c60683ecbea321d723e83f5da6ae5f1c1f9fecc69d9ba96465",
        nodeList: [
            { url: "https://lb.libre.org" },
            { url: "https://libre.eosphere.io" },
            { url: "https://api.libre.eossweden.org" },
            { url: "https://libre-api.eosiomadrid.io" },
            { url: "https://api-libre.nodeone.network:8344" },
            { url: "https://api.libre.genereos.io" },
            { url: "https://api-libre.eosarabia.net" },
            { url: "https://api.libre.blocksindia.com" },
            { url: "https://libre-explorer.edenia.cloud" },
            { url: "https://api.libre.iad.cryptobloks.io" },
            { url: "https://api.libre.pdx.cryptobloks.io" },
            { url: "https://api.libre.cryptobloks.io" },
            { url: "https://libre.greymass.com/" }
        ],
    },
    LIBRETEST: {
        coreSymbol: "LIBRE",
        name: "Libre Testnet",
        testnet: true,
        chainId: "b64646740308df2ee06c6b72f34c0f7fa066d940e831f752db2006fcc2b78dee",
        nodeList: [
            { url: "https://testnet.libre.org" },
            { url: "https://libre.greymass.com/" },
            { url: "https://libre-testnet.eosphere.io" }
        ],
    },
    TLOS: {
        coreSymbol: "TLOS",
        name: "Telos",
        chainId: "4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11",
        nodeList: [
            { url: "https://telos.caleos.io" },
            { url: "https://telos-mainnet.infinitybloc.io" },
            { url: "https://api.telosunlimited.com" },
            { url: "https://telos.eosusa.io" },
            { url: "https://telos.eosphere.io" },
            { url: "https://api.telos.telosgreen.com" },
            { url: "https://api.telosarabia.net" },
            { url: "https://mainnet.persiantelos.com" },
            { url: "https://telosgermany.genereos.io" },
            { url: "https://api.bigironbp.io" },
            { url: "https://api.telos.blocksindia.com" },
            { url: "https://telos.eu.eosamsterdam.net" },
            { url: "https://telos.eosrio.io" },
            { url: "https://bp-telos.y-knot.io" },
            { url: "https://telosapi.ledgerwise.io" },
            { url: "https://telos.cryptolions.io" },
            { url: "https://hyperion.telos.detroitledger.tech" },
            { url: "https://telos.a-dex.xyz" },
        ],
    },
    TLOSTEST: {
        coreSymbol: "TLOS",
        name: "Telos Testnet",
        testnet: true,
        chainId: "1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f3195f33c9f",
        nodeList: [
            { url: "https://telostestnet.greymass.com/" },
            { url: "https://telos-testnet.eosphere.io" }
        ],
    },
    WAX: {
        coreSymbol: "WAX",
        name: "WAX",
        chainId: "1064487b3cd1a897ce03ae5b6a865651747e2e152090f99c1d19d44e01aea5a4",
        nodeList: [
            { url: "https://wax.greymass.com" },
            { url: "https://wax.eosphere.io" },
            { url: "https://wax.blacklusion.io" },
            { url: "https://wax.a-dex.xyz" },
            { url: "https://wax-api.alcor.exchange" },
            { url: "https://wax.cryptolions.io" },
            { url: "https://wax.eosdac.io" },
            { url: "https://wax-history.eosdac.io" },
            { url: "https://api.wax.detroitledger.tech" },
            { url: "https://chain.wax.detroitledger.tech" },
            { url: "https://hyperion.wax.detroitledger.tech" },
            { url: "https://wax.eosusa.io" },
            { url: "https://waxapi.ledgerwise.io" },
            { url: "https://hyperion7.sentnl.io" },
            { url: "https://api2.hivebp.io" },
            { url: "https://api.hivebp.io" },
            { url: "https://wax.hivebp.io" },
            { url: "https://api.waxsweden.org" },
        ],
    },
    WAXTEST: {
        coreSymbol: "WAX",
        name: "WAX Testnet",
        testnet: true,
        chainId: "f16b1833c747c43682f4386fca9cbb327929334a762755ebec17f6f23c9b8a12",
        nodeList: [
            { url: "https://waxtestnet.greymass.com/" },
            { url: "https://api.waxtest.alohaeos.com" },
            { url: "https://waxtest-api.alcor.exchange" },
            { url: "https://wax-testnet.eosphere.io" },
            { url: "https://waxtest.eosdac.io" },
            { url: "https://hyperion.testnet.wax.detroitledger.tech" },
            { url: "https://test.wax.eosusa.io" },
            { url: "https://waxtestnet.ledgerwise.io" },
            { url: "https://testnet.waxsweden.org" },
        ],
    },
    XPR: {
        coreSymbol: "XPR",
        name: "XPR Network",
        chainId: "384da888112027f0321850a169f737c33e53b388aad48b5adace4bab97f437e0",
        nodeList: [
            { url: "https://proton.eosusa.io" },
            { url: "https://api.protonnz.com" },
            { url: "https://proton.protonuk.io" },
            { url: "https://api.totalproton.tech" },
            { url: "https://proton-api.alvosec.com" },
            { url: "https://mainnet-api.xprlabs.org" },
            { url: "https://mainnet.brotonbp.com" },
            { url: "https://api.snipverse.io" },
            { url: "https://api-xpr.blocksforge.com" },
            { url: "https://proton.cryptolions.io" },
            { url: "https://bp-api.storex.io" },
            { url: "https://proton-api.eosiomadrid.io" },
            { url: "https://mainnet.cerebro.host" },
            { url: "https://aa-xprnetwork-main.saltant.io" },
            { url: "https://api-xprnetwork-main.saltant.io" },
            { url: "https://api.cats.vote" },
            { url: "https://protonapi.blocksindia.com" },
            { url: "https://api-proton.nodeone.network:8344" },
            { url: "https://mainchain.simpleblock.org" },
            { url: "https://xpr-mainnet-api.bloxprod.io" },
            { url: "https://proton.eu.eosamsterdam.net" },
        ],
    },
    XPRTEST: {
        coreSymbol: "XPR",
        name: "XPR Testnet",
        testnet: true,
        chainId: "71ee83bcf52142d61019d95f9cc5427ba6a0d7ff8accd9e2088ae2abeaf3d3dd",
        nodeList: [
            { url: "https://test.proton.eosusa.io" },
            { url: "https://testnet-api.alvosec.com" },
            { url: "https://proton-testnet.cryptolions.io" },
            { url: "https://testnet.brotonbp.com" },
            { url: "https://testnet-api.xprcore.com" },
            { url: "https://protontest.eu.eosamsterdam.net" },
            { url: "https://api-xprnetwork-test.saltant.io" },
            { url: "https://testnet-api.xprdata.org" },
            { url: "https://testnet.rockerone.io" },
        ],
    },
};

Object.keys(_blockchains).forEach((key) => {
    _blockchains[key].identifier = key;
});

export const blockchains = _blockchains;
